SUCCESS_OK = 0
ERROR_INVALID_ARGUMENTS = 1
ERROR_UNKNOWN_ARGUMENT = 2
ERROR_NOT_VALID_GAME_FOLDER = 3
ERROR_NO_GAME_FOLDER_SPECIFIED = 4
ERROR_OUTPUT_IS_NOT_EMPTY = 5
ERROR_OUTPUT_IS_NOT_DIRECTORY = 6
